// <auto-generated />
using System;
using MangaMan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaMan.Migrations
{
    [DbContext(typeof(MangaManDbContext))]
    [Migration("20251225140846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MangaMan.Models.MangaArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncFolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasRead")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncFolderId");

                    b.ToTable("MangaArchives");
                });

            modelBuilder.Entity("MangaMan.Models.SyncFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SyncFolders");
                });

            modelBuilder.Entity("MangaMan.Models.MangaArchive", b =>
                {
                    b.HasOne("MangaMan.Models.SyncFolder", "SyncFolder")
                        .WithMany("Entries")
                        .HasForeignKey("SyncFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncFolder");
                });

            modelBuilder.Entity("MangaMan.Models.SyncFolder", b =>
                {
                    b.HasOne("MangaMan.Models.SyncFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MangaMan.Models.SyncFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
